"use client";

import { useEffect, useRef, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { BookCheck, BookOpenCheck, CalendarCheck, Check, Cloud, CloudOff, GraduationCap, Home, LogOut, Nfc, Search, UserRound, Users, X } from "lucide-react";
import { isSupabaseConfigured, supabase } from "@/lib/supabase";

type Tab = "dashboard" | "kehadiran" | "tugasan" | "hafazan" | "pbd" | "profil";
type Student = { id:string; nama:string; tingkatan:string; fotoUrl:string; tarikhDaftar:string; attendance:Record<number,string>; tasks:Record<string,{statusHantar:boolean;tarikhHantar?:string;catatan?:string}>; hafazan:{surahNama:string;ayatMula:number;ayatAkhir:number;tahap:string;tarikhTasmi?:string}[]; pbd:Record<string,number>; ujian:Record<string,number> };
type Task = { id:string; tajuk:string; tarikh:string; tingkatan?:string };
type NdefReader = { scan:(options?:{signal?:AbortSignal})=>Promise<void>; onreading:((e:{serialNumber?:string})=>void)|null };

const initialSessions=["2026-01-15","2026-02-05","2026-02-26","2026-03-19","2026-04-16","2026-05-14","2026-06-18","2026-07-16","2026-08-13","2026-09-17","2026-10-15","2026-11-12"];
const initialTasks:Task[]=[{id:"t1",tajuk:"Latihan Tajwid 1",tarikh:"2026-02-05",tingkatan:"Tingkatan 1"},{id:"t2",tajuk:"Tugasan Kaligrafi",tarikh:"2026-03-19",tingkatan:"Tingkatan 2"},{id:"t3",tajuk:"Latihan Hukum Mad",tarikh:"2026-04-16",tingkatan:"Tingkatan 3"}];
const forms=["Tingkatan 1","Tingkatan 2","Tingkatan 3","Tingkatan 4","Tingkatan 5"];
const nav=[{id:"dashboard",label:"Utama",icon:Home},{id:"kehadiran",label:"Hadir",icon:CalendarCheck},{id:"tugasan",label:"Tugasan",icon:BookOpenCheck},{id:"hafazan",label:"Hafazan",icon:BookCheck},{id:"pbd",label:"PBD",icon:GraduationCap},{id:"profil",label:"Profil",icon:UserRound}] as const;
const today=()=>new Date().toISOString().slice(0,10);
const fmt=(d:string)=>{try{return new Intl.DateTimeFormat("ms-MY",{day:"numeric",month:"short",year:"numeric"}).format(new Date(d))}catch{return d}};
const canon=(v:string)=>v.replace(/[\s:-]/g,"").toUpperCase();
const normalize=(s:Student):Student=>({...s,attendance:s.attendance||{},tasks:s.tasks||{},hafazan:s.hafazan||[],pbd:{Tajwid:s.pbd?.Tajwid??1,Hafazan:s.pbd?.Hafazan??1,Qiraat:s.pbd?.Qiraat??s.pbd?.Tilawah??1,Tarannum:s.pbd?.Tarannum??1},ujian:s.ujian||{"Ujian 1":0,UASA:0}});

export default function HomePage(){
 const [tab,setTab]=useState<Tab>("dashboard"),[students,setStudents]=useState<Student[]>([]),[tasks,setTasks]=useState<Task[]>(initialTasks),[sessions,setSessions]=useState(initialSessions);
 const [sessionNo,setSessionNo]=useState(1),[form,setForm]=useState(""),[search,setSearch]=useState(""),[authSession,setAuthSession]=useState<Session|null>(null),[authChecked,setAuthChecked]=useState(!isSupabaseConfigured),[backendLoaded,setBackendLoaded]=useState(!isSupabaseConfigured),[sync,setSync]=useState<"local"|"saving"|"synced"|"offline">(isSupabaseConfigured?"saving":"local");
 const [scan,setScan]=useState<"idle"|"scanning"|"unsupported">("idle"),[lastScan,setLastScan]=useState(""),[toast,setToast]=useState("");
 const abortRef=useRef<AbortController|null>(null), studentsRef=useRef<Student[]>([]), lastTap=useRef<{uid:string;at:number}>({uid:"",at:0});
 useEffect(()=>{studentsRef.current=students},[students]);
 useEffect(()=>{const saved=localStorage.getItem("kkq-pwa-data-v1");if(saved)try{const x=JSON.parse(saved);setStudents((x.students||[]).map(normalize));setTasks(x.tasks||initialTasks);setSessions(x.sessions?.length?x.sessions:initialSessions)}catch{};if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{})},[]);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>{setAuthSession(data.session);setAuthChecked(true)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setAuthSession(s);setAuthChecked(true);if(!s)setBackendLoaded(false)});return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{const c=supabase;if(!c||!authSession)return;let active=true;setSync("saving");c.rpc("get_kkq_state").then(async({data,error})=>{if(!active)return;if(error){setSync("offline");setBackendLoaded(true);return}const st=data as {students:Student[];tasks:Task[];sessions:string[]}|null;if(st?.sessions?.length){setStudents((st.students||[]).map(normalize));setTasks(st.tasks||[]);setSessions(st.sessions)}else await c.rpc("replace_kkq_state",{p_students:students,p_tasks:tasks,p_sessions:sessions});setBackendLoaded(true);setSync("synced")});return()=>{active=false}},[authSession?.user.id]);
 useEffect(()=>{const snap={students,tasks,sessions};localStorage.setItem("kkq-pwa-data-v1",JSON.stringify(snap));const c=supabase;if(!c||!authSession||!backendLoaded)return;setSync("saving");const t=window.setTimeout(async()=>{const {error}=await c.rpc("replace_kkq_state",{p_students:students,p_tasks:tasks,p_sessions:sessions});setSync(error?"offline":"synced")},450);return()=>clearTimeout(t)},[students,tasks,sessions,authSession?.user.id,backendLoaded]);
 useEffect(()=>()=>abortRef.current?.abort(),[]);
 const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),2200)};
 const visible=students.filter(s=>(!form||s.tingkatan===form)&&(!search||s.nama.toLowerCase().includes(search.toLowerCase())||s.id.toLowerCase().includes(search.toLowerCase())));
 const present=students.filter(s=>!!s.attendance?.[sessionNo]);
 function stopScan(){abortRef.current?.abort();abortRef.current=null;setScan("idle")}
 function recordUid(raw:string){const uid=canon(raw),now=Date.now();if(!uid)return;if(lastTap.current.uid===uid&&now-lastTap.current.at<1400)return;lastTap.current={uid,at:now};const found=studentsRef.current.find(s=>canon(s.id)===uid);if(!found){setLastScan("Kad belum didaftarkan");notify("⚠️ Kad NFC belum didaftarkan");navigator.vibrate?.([40,60,40]);return}if(found.attendance?.[sessionNo]){setLastScan(`${found.nama} — sudah hadir`);notify(`⚠️ ${found.nama} sudah direkodkan`);navigator.vibrate?.([35,45,35]);return}const stamp=new Date().toISOString();setStudents(xs=>xs.map(s=>s.id===found.id?{...s,attendance:{...s.attendance,[sessionNo]:stamp}}:s));setLastScan(`${found.nama} — HADIR`);notify(`✓ ${found.nama} — HADIR`);navigator.vibrate?.(80)}
 async function startFastScan(){stopScan();setScan("scanning");setLastScan("");const NDEF=(window as unknown as {NDEFReader?:new()=>NdefReader}).NDEFReader;if(!NDEF){setScan("unsupported");return}try{const ctrl=new AbortController();abortRef.current=ctrl;const r=new NDEF();await r.scan({signal:ctrl.signal});r.onreading=e=>recordUid(e.serialNumber||"")}catch(e){if((e as Error)?.name!=="AbortError")setScan("unsupported")}}
 function simulate(){const candidate=students.find(s=>!s.attendance?.[sessionNo])||students[0];if(!candidate){notify("Belum ada murid");return}recordUid(candidate.id)}
 if(!authChecked||(authSession&&!backendLoaded))return <Center text="Memuatkan Smart KKQ…"/>;
 if(isSupabaseConfigured&&!authSession)return <Login/>;
 return <main className="min-h-dvh bg-[#f4f6f3] pb-24 text-slate-900"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/90 px-4 py-3 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center gap-3"><img src="/icons/icon-192.png" className="size-9 rounded-xl" alt=""/><div><b>Smart KKQ</b><p className="flex items-center gap-1 text-[11px] text-slate-500">{sync==="offline"?<CloudOff size={11}/>:<Cloud size={11}/>} {sync==="saving"?"Menyegerak…":sync==="synced"?"Disimpan di Supabase":sync==="offline"?"Luar talian":"Simpanan peranti"}</p></div>{authSession&&<button onClick={()=>supabase?.auth.signOut()} className="ml-auto rounded-xl bg-slate-100 p-2.5"><LogOut size={16}/></button>}</div></header>
 <div className="mx-auto max-w-5xl px-4 py-5">{tab==="dashboard"&&<Dashboard students={students} sessions={sessions} tasks={tasks}/>} {tab==="kehadiran"&&<Attendance students={students} sessions={sessions} sessionNo={sessionNo} setSessionNo={setSessionNo} setSessions={setSessions} scan={scan} start={startFastScan} stop={stopScan} simulate={simulate} last={lastScan}/>} {tab==="tugasan"&&<Tasks students={students} tasks={tasks}/>} {tab==="hafazan"&&<SimpleList title="Perkembangan Hafazan" students={students} mode="hafazan"/>} {tab==="pbd"&&<SimpleList title="PBD & Markah" students={students} mode="pbd"/>} {tab==="profil"&&<Profile students={visible} form={form} setForm={setForm} search={search} setSearch={setSearch}/>}</div>
 <nav className="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 px-1 pb-[max(.35rem,env(safe-area-inset-bottom))] pt-1"><div className="mx-auto grid max-w-xl grid-cols-6">{nav.map(i=><button key={i.id} onClick={()=>{stopScan();setTab(i.id)}} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-semibold ${tab===i.id?"text-emerald-900":"text-slate-400"}`}><i.icon size={18}/>{i.label}</button>)}</div></nav>
 {toast&&<div className="fixed left-1/2 top-20 z-50 w-[calc(100%-2rem)] max-w-sm -translate-x-1/2 rounded-2xl border bg-white p-3 text-sm font-bold shadow-xl"><Check className="mr-2 inline text-emerald-700" size={17}/>{toast}</div>}</main>
}

function Attendance({students,sessions,sessionNo,setSessionNo,setSessions,scan,start,stop,simulate,last}:{students:Student[];sessions:string[];sessionNo:number;setSessionNo:(n:number)=>void;setSessions:(s:string[])=>void;scan:string;start:()=>void;stop:()=>void;simulate:()=>void;last:string}){const present=students.filter(s=>s.attendance?.[sessionNo]);return <div className="space-y-4"><Title title="Kehadiran KKQ" note="Pilih sesi, kemudian imbas kad NFC murid satu demi satu."/><section className="card"><label className="text-xs font-bold text-slate-500">Pilih sesi</label><select value={sessionNo} onChange={e=>{stop();setSessionNo(Number(e.target.value))}} className="input mt-2">{sessions.map((d,i)=><option key={i} value={i+1}>Sesi {i+1} — {fmt(d)}</option>)}</select><input type="date" value={sessions[sessionNo-1]||""} onChange={e=>setSessions(sessions.map((d,i)=>i===sessionNo-1?e.target.value:d))} className="input mt-2"/></section>
 <section className={`rounded-[1.5rem] border p-5 ${scan==="scanning"?"border-emerald-300 bg-emerald-50":"border-slate-200 bg-white"}`}><div className="flex items-center gap-4"><span className={`grid size-16 place-items-center rounded-full ${scan==="scanning"?"animate-pulse bg-emerald-200 text-emerald-900":"bg-slate-100 text-slate-500"}`}><Nfc size={30}/></span><div><b className="text-lg">{scan==="scanning"?"Pengimbas aktif":"Imbas Kehadiran Pantas"}</b><p className="text-sm text-slate-500">{scan==="scanning"?"Sentuh kad murid. Scanner kekal aktif untuk kad seterusnya.":scan==="unsupported"?"Web NFC tidak tersedia. Gunakan Chrome Android melalui HTTPS.":"Tekan mula untuk imbas secara berterusan."}</p></div></div>{last&&<p className="mt-4 rounded-xl bg-white p-3 text-sm font-bold text-emerald-900">{last}</p>}<div className="mt-4 grid grid-cols-2 gap-2">{scan==="scanning"?<button onClick={stop} className="col-span-2 rounded-2xl bg-slate-900 py-3.5 font-bold text-white"><X className="mr-2 inline" size={17}/>Hentikan Imbasan</button>:<button onClick={start} className="col-span-2 rounded-2xl bg-[#163c35] py-3.5 font-bold text-white"><Nfc className="mr-2 inline" size={18}/>Mula Imbas NFC</button>}<button onClick={simulate} className="col-span-2 rounded-2xl bg-slate-100 py-3 text-sm font-bold">Simulasi kad</button></div></section>
 <section className="card"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase text-slate-400">Sesi {sessionNo}</p><b className="text-2xl">{present.length}/{students.length}</b><p className="text-xs text-slate-500">murid hadir</p></div><span className="rounded-2xl bg-emerald-100 px-4 py-2 font-black text-emerald-800">{students.length?Math.round(present.length/students.length*100):0}%</span></div></section><section><h3 className="mb-2 font-bold">Hadir terkini</h3><div className="space-y-2">{present.slice().reverse().slice(0,30).map(s=><Row key={s.id} s={s} status="Hadir"/>)}</div></section></div>}
function Dashboard({students,sessions,tasks}:{students:Student[];sessions:string[];tasks:Task[]}){const total=students.reduce((n,s)=>n+Object.keys(s.attendance||{}).length,0);return <div className="space-y-4"><Title title="Smart KKQ" note="Ringkasan rekod semasa"/><div className="grid grid-cols-2 gap-3"><Stat icon={Users} n={students.length} label="Murid"/><Stat icon={CalendarCheck} n={total} label="Rekod hadir"/><Stat icon={BookOpenCheck} n={tasks.length} label="Tugasan"/><Stat icon={CalendarCheck} n={sessions.length} label="Sesi"/></div></div>}
function Tasks({students,tasks}:{students:Student[];tasks:Task[]}){return <div className="space-y-4"><Title title="Tugasan Buku" note="Rekod tugasan sedia ada"/>{tasks.map(t=>{const group=students.filter(s=>!t.tingkatan||s.tingkatan===t.tingkatan),done=group.filter(s=>s.tasks?.[t.id]?.statusHantar).length;return <section className="card" key={t.id}><b>{t.tajuk}</b><p className="text-xs text-slate-500">{t.tingkatan||"Semua"} • {fmt(t.tarikh)}</p><p className="mt-3 text-sm font-bold">{done}/{group.length} telah hantar</p></section>})}</div>}
function SimpleList({title,students,mode}:{title:string;students:Student[];mode:"hafazan"|"pbd"}){const [f,setF]=useState("");const list=students.filter(s=>!f||s.tingkatan===f);return <div className="space-y-4"><Title title={title} note="Pilih tingkatan untuk melihat rekod"/><Filter form={f} setForm={setF}/>{f&&<div className="space-y-2">{list.map(s=><Row key={s.id} s={s} status={mode==="hafazan"?`${s.hafazan?.length||0} rekod hafazan`:`TP Hafazan ${s.pbd?.Hafazan||1}`}/>)}</div>}</div>}
function Profile({students,form,setForm,search,setSearch}:{students:Student[];form:string;setForm:(v:string)=>void;search:string;setSearch:(v:string)=>void}){return <div className="space-y-4"><Title title="Profil Murid" note="Cari murid mengikut tingkatan"/><Filter form={form} setForm={setForm}/>{form&&<div className="relative"><Search className="absolute left-3 top-3.5 text-slate-400" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari nama / UID" className="input pl-10"/></div>}<div className="space-y-2">{students.map(s=><Row key={s.id} s={s} status={s.tingkatan}/>)}</div></div>}
function Filter({form,setForm}:{form:string;setForm:(v:string)=>void}){return <select value={form} onChange={e=>setForm(e.target.value)} className="input"><option value="">Pilih Tingkatan</option>{forms.map(f=><option key={f}>{f}</option>)}</select>}
function Row({s,status}:{s:Student;status:string}){return <div className="card flex items-center gap-3 !p-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-emerald-50 font-black text-emerald-800">{s.nama.slice(0,1)}</span><div className="min-w-0"><b className="block truncate text-sm">{s.nama}</b><p className="truncate text-xs text-slate-500">{status}</p></div></div>}
function Title({title,note}:{title:string;note:string}){return <div><h2 className="text-2xl font-black tracking-tight">{title}</h2><p className="mt-1 text-sm text-slate-500">{note}</p></div>}
function Stat({icon:Icon,n,label}:{icon:typeof Users;n:number;label:string}){return <div className="card"><Icon size={19} className="text-emerald-700"/><b className="mt-3 block text-2xl">{n}</b><span className="text-xs text-slate-500">{label}</span></div>}
function Center({text}:{text:string}){return <main className="grid min-h-dvh place-items-center bg-[#f4f6f3]"><b>{text}</b></main>}
function Login(){const [email,setEmail]=useState(""),[pin,setPin]=useState(""),[error,setError]=useState("");async function go(){if(!supabase)return;const {error:e}=await supabase.auth.signInWithPassword({email:email.trim(),password:pin});if(e)setError("E-mel atau PIN tidak sah.")}return <main className="grid min-h-dvh place-items-center bg-[#f4f6f3] p-5"><section className="w-full max-w-sm rounded-[2rem] bg-white p-6 shadow-xl"><h1 className="text-2xl font-black">Log masuk guru</h1><p className="mt-1 text-sm text-slate-500">Smart KKQ</p><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="E-mel guru" className="input mt-6"/><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="PIN / kata laluan" className="input mt-3"/><button onClick={go} className="mt-4 w-full rounded-2xl bg-[#163c35] py-4 font-bold text-white">Log masuk</button>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</section></main>}
